### ISSUE TITLE
Delegation of work for Sprint 1

### ISSUE THREAD

**Issue by WilliamDPrince** [Intro-to-SE-Lab-Fall-20/Group-7#2]
How would we like to delegate the work for sprint 1?

**Comment by mn834** [comment]
Good question GlizzyOperator, I will do what is best for the team!

**Comment by WilliamDPrince** [comment]
I am going to work on filling out the SRS Document and setting up the first User Story

**Comment by alexbui831** [comment]
I believe the divide and conquer strategy would work my fellow GlizzyOperator!
