### ISSUE TITLE
Choice of template

### ISSUE THREAD

**Issue by WilliamDPrince** [Intro-to-SE-Lab-Fall-20/Group-7#5]
In order to begin the basis of the website, we need to first import a template. It is usually a combination of html, css, python, sqlite for the database, etc. I have the basic skeleton of a website with most of these files, but the template will set the framework making this a lot easier.

We can find templates on github or any other website, but we must cite it in our user stories and the wiki read.me to avoid any potential plagiarism.

**Comment by MagicalChicken3** [comment]
https://github.com/tugrankenger/login-template  this might be helpful

**Comment by WilliamDPrince** [comment]
After review. Materialize.css was used for its modularity.
