### ISSUE TITLE
Saving Logins

### ISSUE THREAD

**Issue by MagicalChicken3** [Intro-to-SE-Lab-Fall-20/Group-7#6]
How will we be able to save user login information to a database.

**Comment by MagicalChicken3** [comment]
We will also need it to check the database to verify to users information

**Comment by WilliamDPrince** [comment]
In the register.py and views.py file in my pull request, you will find that the use makes a POST request that is saved within the database when submitted. It includes some if statements to verify the information when login is made. The register function stores the user's data into the database.
